
var Matrix = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Matrix) {
  Matrix = Matrix || {};


var g;g||(g=typeof Matrix !== 'undefined' ? Matrix : {});var aa,ca;g.ready=new Promise(function(a,b){aa=a;ca=b});var q={},v;for(v in g)g.hasOwnProperty(v)&&(q[v]=g[v]);var da=!1,w=!1,ea=!1,fa=!1;da="object"===typeof window;w="function"===typeof importScripts;ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;fa=!da&&!ea&&!w;var x="",ha,ia,y,ja,ka;
if(ea)x=w?require("path").dirname(x)+"/":__dirname+"/",ha=function(a,b){ja||(ja=require("fs"));ka||(ka=require("path"));a=ka.normalize(a);return ja.readFileSync(a,b?null:"utf8")},y=function(a){a=ha(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",z),g.inspect=function(){return"[Emscripten Module object]"};else if(fa)"undefined"!=
typeof read&&(ha=function(a){return read(a)}),y=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(da||w)w?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptDir&&(x=_scriptDir),
0!==x.indexOf("blob:")?x=x.substr(0,x.lastIndexOf("/")+1):x="",ha=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},w&&(y=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
g.print||console.log.bind(console);var A=g.printErr||console.warn.bind(console);for(v in q)q.hasOwnProperty(v)&&(g[v]=q[v]);q=null;var B;g.wasmBinary&&(B=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&z("no native wasm support detected");var la,ma=!1;function assert(a,b){a||z("Assertion failed: "+b)}var na="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function pa(a,b,c){var d=C;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0}}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function ra(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&sa[c];)++c;c<<=1;if(32<c-a&&qa)return qa.decode(C.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=D[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function ta(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d}function ua(a){return 2*a.length}
function va(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function wa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}
function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ya,za,C,D,sa,E,F,Aa,Ba,Ca,Da;function Ea(){var a=la.buffer;ya=a;g.HEAP8=za=new Int8Array(a);g.HEAP16=D=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=C=new Uint8Array(a);g.HEAPU16=sa=new Uint16Array(a);g.HEAPU32=F=new Uint32Array(a);g.HEAPF32=Aa=new Float32Array(a);g.HEAPF64=Ba=new Float64Array(a);g.HEAP64=Ca=new BigInt64Array(a);g.HEAPU64=Da=new BigUint64Array(a)}
var Fa,Ga=[],Ha=[],Ia=[];function Ka(){var a=g.preRun.shift();Ga.unshift(a)}var G=0,La=null,H=null;g.preloadedImages={};g.preloadedAudios={};function z(a){if(g.onAbort)g.onAbort(a);A(a);ma=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ca(a);throw a;}function Ma(){return I.startsWith("data:application/octet-stream;base64,")}var I;I="a.out.wasm";if(!Ma()){var Na=I;I=g.locateFile?g.locateFile(Na,x):x+Na}
function Oa(){var a=I;try{if(a==I&&B)return new Uint8Array(B);if(y)return y(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Pa(){if(!B&&(da||w)){if("function"===typeof fetch&&!I.startsWith("file://"))return fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Oa()});if(ia)return new Promise(function(a,b){ia(I,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Oa()})}
function Qa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.ja;"number"===typeof c?void 0===b.U?Fa.get(c)():Fa.get(c)(b.U):c(void 0===b.U?null:b.U)}}}function J(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}var Ra=void 0;function K(a){for(var b="";C[a];)b+=Ra[C[a++]];return b}var L={},M={},Sa={};
function Ta(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ua(a,b){a=Ta(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Va(a){var b=Error,c=Ua(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var N=void 0;function O(a){throw new N(a);}var Wa=void 0;function Xa(a){throw new Wa(a);}
function P(a,b,c){function d(h){h=c(h);h.length!==a.length&&Xa("Mismatched type converter count");for(var n=0;n<a.length;++n)Q(a[n],h[n])}a.forEach(function(h){Sa[h]=b});var e=Array(b.length),f=[],l=0;b.forEach(function(h,n){M.hasOwnProperty(h)?e[n]=M[h]:(f.push(h),L.hasOwnProperty(h)||(L[h]=[]),L[h].push(function(){e[n]=M[h];++l;l===f.length&&d(e)}))});0===f.length&&d(e)}
function Q(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||O('type "'+d+'" must have a positive integer typeid pointer');if(M.hasOwnProperty(a)){if(c.ba)return;O("Cannot register type '"+d+"' twice")}M[a]=b;delete Sa[a];L.hasOwnProperty(a)&&(b=L[a],delete L[a],b.forEach(function(e){e()}))}
function Ya(a,b,c){switch(b){case 0:return c?function(d){return za[d]}:function(d){return C[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return sa[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return F[d>>2]};case 3:return c?function(d){return Ca[d>>3]}:function(d){return Da[d>>3]};default:throw new TypeError("Unknown integer type: "+a);}}
function Za(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}function $a(a){return{count:a.count,M:a.M,O:a.O,C:a.C,D:a.D,G:a.G,H:a.H}}function ab(a){O(a.A.D.B.name+" instance already deleted")}var bb=!1;function cb(){}function db(a){--a.count.value;0===a.count.value&&(a.G?a.H.L(a.G):a.D.B.L(a.C))}
function S(a){if("undefined"===typeof FinalizationGroup)return S=function(b){return b},a;bb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.C?db(c):console.warn("object already deleted: "+c.C)});S=function(b){bb.register(b,b.A,b.A);return b};cb=function(b){bb.unregister(b.A)};return S(a)}var T=void 0,U=[];function eb(){for(;U.length;){var a=U.pop();a.A.M=!1;a["delete"]()}}function V(){}var fb={};
function gb(a,b,c){if(void 0===a[b].F){var d=a[b];a[b]=function(){a[b].F.hasOwnProperty(arguments.length)||O("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].F+")!");return a[b].F[arguments.length].apply(this,arguments)};a[b].F=[];a[b].F[d.R]=d}}
function hb(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].F&&void 0!==g[a].F[c])&&O("Cannot register public name '"+a+"' twice"),gb(g,a,a),g.hasOwnProperty(c)&&O("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].F[c]=b):(g[a]=b,void 0!==c&&(g[a].la=c))}function ib(a,b,c,d,e,f,l,h){this.name=a;this.constructor=b;this.N=c;this.L=d;this.I=e;this.$=f;this.P=l;this.Z=h;this.ea=[]}
function jb(a,b,c){for(;b!==c;)b.P||O("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.P(a),b=b.I;return a}function kb(a,b){if(null===b)return this.V&&O("null is not a valid "+this.name),0;b.A||O('Cannot pass "'+J(b)+'" as a '+this.name);b.A.C||O("Cannot pass deleted object as a pointer of type "+this.name);return jb(b.A.C,b.A.D.B,this.B)}
function lb(a,b){if(null===b){this.V&&O("null is not a valid "+this.name);if(this.T){var c=this.fa();null!==a&&a.push(this.L,c);return c}return 0}b.A||O('Cannot pass "'+J(b)+'" as a '+this.name);b.A.C||O("Cannot pass deleted object as a pointer of type "+this.name);!this.S&&b.A.D.S&&O("Cannot convert argument of type "+(b.A.H?b.A.H.name:b.A.D.name)+" to parameter type "+this.name);c=jb(b.A.C,b.A.D.B,this.B);if(this.T)switch(void 0===b.A.G&&O("Passing raw pointer to smart pointer is illegal"),this.ia){case 0:b.A.H===
this?c=b.A.G:O("Cannot convert argument of type "+(b.A.H?b.A.H.name:b.A.D.name)+" to parameter type "+this.name);break;case 1:c=b.A.G;break;case 2:if(b.A.H===this)c=b.A.G;else{var d=b.clone();c=this.ga(c,mb(function(){d["delete"]()}));null!==a&&a.push(this.L,c)}break;default:O("Unsupporting sharing policy")}return c}
function nb(a,b){if(null===b)return this.V&&O("null is not a valid "+this.name),0;b.A||O('Cannot pass "'+J(b)+'" as a '+this.name);b.A.C||O("Cannot pass deleted object as a pointer of type "+this.name);b.A.D.S&&O("Cannot convert argument of type "+b.A.D.name+" to parameter type "+this.name);return jb(b.A.C,b.A.D.B,this.B)}function ob(a){return this.fromWireType(F[a>>2])}function pb(a,b,c){if(b===c)return a;if(void 0===c.I)return null;a=pb(a,b,c.I);return null===a?null:c.Z(a)}var qb={};
function tb(a,b){for(void 0===b&&O("ptr should not be undefined");a.I;)b=a.P(b),a=a.I;return qb[b]}function ub(a,b){b.D&&b.C||Xa("makeClassHandle requires ptr and ptrType");!!b.H!==!!b.G&&Xa("Both smartPtrType and smartPtr must be specified");b.count={value:1};return S(Object.create(a,{A:{value:b}}))}function W(a,b,c,d){this.name=a;this.B=b;this.V=c;this.S=d;this.T=!1;this.L=this.ga=this.fa=this.X=this.ia=this.da=void 0;void 0!==b.I?this.toWireType=lb:(this.toWireType=d?kb:nb,this.J=null)}
function vb(a,b,c){g.hasOwnProperty(a)||Xa("Replacing nonexistant public symbol");void 0!==g[a].F&&void 0!==c?g[a].F[c]=b:(g[a]=b,g[a].R=c)}function X(a,b){a=K(a);var c=Fa.get(b);"function"!==typeof c&&O("unknown function pointer with signature "+a+": "+b);return c}var wb=void 0;function xb(a){a=yb(a);var b=K(a);Y(a);return b}function zb(a,b){function c(f){e[f]||M[f]||(Sa[f]?Sa[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new wb(a+": "+d.map(xb).join([", "]));}
function Ab(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}function Bb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Cb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ua(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Db(a,b,c,d,e){var f=b.length;2>f&&O("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,h=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].J){h=!0;break}var n="void"!==b[0].name,k="",m="";for(c=0;c<f-2;++c)k+=(0!==c?", ":"")+"arg"+c,m+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Ta(a)+"("+k+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";h&&(a+="var destructors = [];\n");var p=h?"destructors":"null";k="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[O,d,e,Bb,b[0],b[1]];l&&(a+="var thisWired = classParam.toWireType("+p+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+p+", arg"+c+"); // "+b[c+2].name+"\n",k.push("argType"+c),d.push(b[c+2]);l&&(m="thisWired"+(0<m.length?", ":"")+m);a+=(n?"var rv = ":"")+"invoker(fn"+(0<m.length?", ":"")+m+");\n";if(h)a+=
"runDestructors(destructors);\n";else for(c=l?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].J&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",k.push(f+"_dtor"),d.push(b[c].J));n&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");k.push(a+"}\n");return Cb(k).apply(null,d)}var Eb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function mb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Eb.length?Eb.pop():Z.length;Z[b]={ha:1,value:a};return b}}function Fb(a,b){switch(b){case 2:return function(c){return this.fromWireType(Aa[c>>2])};case 3:return function(c){return this.fromWireType(Ba[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}for(var Gb=Array(256),Hb=0;256>Hb;++Hb)Gb[Hb]=String.fromCharCode(Hb);Ra=Gb;N=g.BindingError=Va("BindingError");
Wa=g.InternalError=Va("InternalError");V.prototype.isAliasOf=function(a){if(!(this instanceof V&&a instanceof V))return!1;var b=this.A.D.B,c=this.A.C,d=a.A.D.B;for(a=a.A.C;b.I;)c=b.P(c),b=b.I;for(;d.I;)a=d.P(a),d=d.I;return b===d&&c===a};V.prototype.clone=function(){this.A.C||ab(this);if(this.A.O)return this.A.count.value+=1,this;var a=S(Object.create(Object.getPrototypeOf(this),{A:{value:$a(this.A)}}));a.A.count.value+=1;a.A.M=!1;return a};
V.prototype["delete"]=function(){this.A.C||ab(this);this.A.M&&!this.A.O&&O("Object already scheduled for deletion");cb(this);db(this.A);this.A.O||(this.A.G=void 0,this.A.C=void 0)};V.prototype.isDeleted=function(){return!this.A.C};V.prototype.deleteLater=function(){this.A.C||ab(this);this.A.M&&!this.A.O&&O("Object already scheduled for deletion");U.push(this);1===U.length&&T&&T(eb);this.A.M=!0;return this};W.prototype.aa=function(a){this.X&&(a=this.X(a));return a};
W.prototype.W=function(a){this.L&&this.L(a)};W.prototype.argPackAdvance=8;W.prototype.readValueFromPointer=ob;W.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
W.prototype.fromWireType=function(a){function b(){return this.T?ub(this.B.N,{D:this.da,C:c,H:this,G:a}):ub(this.B.N,{D:this,C:a})}var c=this.aa(a);if(!c)return this.W(a),null;var d=tb(this.B,c);if(void 0!==d){if(0===d.A.count.value)return d.A.C=c,d.A.G=a,d.clone();d=d.clone();this.W(a);return d}d=this.B.$(c);d=fb[d];if(!d)return b.call(this);d=this.S?d.Y:d.pointerType;var e=pb(c,this.B,d.B);return null===e?b.call(this):this.T?ub(d.B.N,{D:d,C:e,H:this,G:a}):ub(d.B.N,{D:d,C:e})};
g.getInheritedInstanceCount=function(){return Object.keys(qb).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in qb)qb.hasOwnProperty(b)&&a.push(qb[b]);return a};g.flushPendingDeletes=eb;g.setDelayFunction=function(a){T=a;U.length&&T&&T(eb)};wb=g.UnboundTypeError=Va("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
var Jb={j:function(a,b,c,d,e){b=K(b);c=Za(c);var f=-1!=b.indexOf("u");f&&(e=(BigInt(1)<<BigInt(64))-BigInt(1));Q(a,{name:b,fromWireType:function(l){return l},toWireType:function(l,h){if("bigint"!==typeof h)throw new TypeError('Cannot convert "'+J(h)+'" to '+this.name);if(h<d||h>e)throw new TypeError('Passing a number "'+J(h)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return h},argPackAdvance:8,readValueFromPointer:Ya(b,c,!f),J:null})},
l:function(a,b,c,d,e){var f=Za(c);b=K(b);Q(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var h=za;else if(2===c)h=D;else if(4===c)h=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[l>>f])},J:null})},f:function(a,b,c,d,e,f,l,h,n,k,m,p,r){m=K(m);f=X(e,f);h&&(h=X(l,h));k&&(k=X(n,k));r=X(p,r);var u=Ta(m);hb(u,function(){zb("Cannot construct "+m+" due to unbound types",
[d])});P([a,b,c],d?[d]:[],function(t){t=t[0];if(d){var oa=t.B;var ba=oa.N}else ba=V.prototype;t=Ua(u,function(){if(Object.getPrototypeOf(this)!==Ja)throw new N("Use 'new' to construct "+m);if(void 0===R.K)throw new N(m+" has no accessible constructor");var rb=R.K[arguments.length];if(void 0===rb)throw new N("Tried to invoke ctor of "+m+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(R.K).toString()+") parameters instead!");return rb.apply(this,arguments)});var Ja=
Object.create(ba,{constructor:{value:t}});t.prototype=Ja;var R=new ib(m,t,Ja,r,oa,f,h,k);oa=new W(m,R,!0,!1);ba=new W(m+"*",R,!1,!1);var sb=new W(m+" const*",R,!1,!0);fb[a]={pointerType:ba,Y:sb};vb(u,t);return[oa,ba,sb]})},c:function(a,b,c,d,e,f){assert(0<b);var l=Ab(b,c);e=X(d,e);var h=[f],n=[];P([],[a],function(k){k=k[0];var m="constructor "+k.name;void 0===k.B.K&&(k.B.K=[]);if(void 0!==k.B.K[b-1])throw new N("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+
k.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");k.B.K[b-1]=function(){zb("Cannot construct "+k.name+" due to unbound types",l)};P([],l,function(p){k.B.K[b-1]=function(){arguments.length!==b-1&&O(m+" called with "+arguments.length+" arguments, expected "+(b-1));n.length=0;h.length=b;for(var r=1;r<b;++r)h[r]=p[r].toWireType(n,arguments[r-1]);r=e.apply(null,h);Bb(n);return p[0].fromWireType(r)};return[]});return[]})},a:function(a,b,c,d,e,
f,l,h){var n=Ab(c,d);b=K(b);f=X(e,f);P([],[a],function(k){function m(){zb("Cannot call "+p+" due to unbound types",n)}k=k[0];var p=k.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&k.B.ea.push(b);var r=k.B.N,u=r[b];void 0===u||void 0===u.F&&u.className!==k.name&&u.R===c-2?(m.R=c-2,m.className=k.name,r[b]=m):(gb(r,b,p),r[b].F[c-2]=m);P([],n,function(t){t=Db(p,t,k,f,l);void 0===r[b].F?(t.R=c-2,r[b]=t):r[b].F[c-2]=t;return[]});return[]})},k:function(a,b){b=K(b);Q(a,{name:b,fromWireType:function(c){var d=
Z[c].value;4<c&&0===--Z[c].ha&&(Z[c]=void 0,Eb.push(c));return d},toWireType:function(c,d){return mb(d)},argPackAdvance:8,readValueFromPointer:ob,J:null})},i:function(a,b,c){c=Za(c);b=K(b);Q(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+J(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Fb(b,c),J:null})},b:function(a,b,c,d,e,f){var l=Ab(b,c);a=K(a);e=X(d,e);hb(a,function(){zb("Cannot call "+
a+" due to unbound types",l)},b-1);P([],l,function(h){h=[h[0],null].concat(h.slice(1));vb(a,Db(a,h,null,e,f),b-1);return[]})},e:function(a,b,c,d,e){function f(k){return k}b=K(b);-1===e&&(e=4294967295);var l=Za(c);if(0===d){var h=32-8*c;f=function(k){return k<<h>>>h}}var n=b.includes("unsigned");Q(a,{name:b,fromWireType:f,toWireType:function(k,m){if("number"!==typeof m&&"boolean"!==typeof m)throw new TypeError('Cannot convert "'+J(m)+'" to '+this.name);if(m<d||m>e)throw new TypeError('Passing a number "'+
J(m)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return n?m>>>0:m|0},argPackAdvance:8,readValueFromPointer:Ya(b,l,0!==d),J:null})},d:function(a,b,c){function d(f){f>>=2;var l=F;return new e(ya,l[f+1],l[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=K(c);Q(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ba:!0})},h:function(a,b){b=K(b);var c="std::string"===
b;Q(a,{name:b,fromWireType:function(d){var e=F[d>>2];if(c)for(var f=d+4,l=0;l<=e;++l){var h=d+4+l;if(l==e||0==C[h]){if(f){var n=f;var k=C,m=n+(h-f);for(f=n;k[f]&&!(f>=m);)++f;if(16<f-n&&k.subarray&&na)n=na.decode(k.subarray(n,f));else{for(m="";n<f;){var p=k[n++];if(p&128){var r=k[n++]&63;if(192==(p&224))m+=String.fromCharCode((p&31)<<6|r);else{var u=k[n++]&63;p=224==(p&240)?(p&15)<<12|r<<6|u:(p&7)<<18|r<<12|u<<6|k[n++]&63;65536>p?m+=String.fromCharCode(p):(p-=65536,m+=String.fromCharCode(55296|p>>
10,56320|p&1023))}}else m+=String.fromCharCode(p)}n=m}}else n="";if(void 0===t)var t=n;else t+=String.fromCharCode(0),t+=n;f=h+1}}else{t=Array(e);for(l=0;l<e;++l)t[l]=String.fromCharCode(C[d+4+l]);t=t.join("")}Y(d);return t},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||O("Cannot pass non-string to std::string");var l=(c&&f?function(){for(var k=0,m=0;m<e.length;++m){var p=
e.charCodeAt(m);55296<=p&&57343>=p&&(p=65536+((p&1023)<<10)|e.charCodeAt(++m)&1023);127>=p?++k:k=2047>=p?k+2:65535>=p?k+3:k+4}return k}:function(){return e.length})(),h=Ib(4+l+1);F[h>>2]=l;if(c&&f)pa(e,h+4,l+1);else if(f)for(f=0;f<l;++f){var n=e.charCodeAt(f);255<n&&(Y(h),O("String has UTF-16 code units that do not fit in 8 bits"));C[h+4+f]=n}else for(f=0;f<l;++f)C[h+4+f]=e[f];null!==d&&d.push(Y,h);return h},argPackAdvance:8,readValueFromPointer:ob,J:function(d){Y(d)}})},g:function(a,b,c){c=K(c);
if(2===b){var d=ra;var e=ta;var f=ua;var l=function(){return sa};var h=1}else 4===b&&(d=va,e=wa,f=xa,l=function(){return F},h=2);Q(a,{name:c,fromWireType:function(n){for(var k=F[n>>2],m=l(),p,r=n+4,u=0;u<=k;++u){var t=n+4+u*b;if(u==k||0==m[t>>h])r=d(r,t-r),void 0===p?p=r:(p+=String.fromCharCode(0),p+=r),r=t+b}Y(n);return p},toWireType:function(n,k){"string"!==typeof k&&O("Cannot pass non-string to C++ string type "+c);var m=f(k),p=Ib(4+m+b);F[p>>2]=m>>h;e(k,p+4,m+b);null!==n&&n.push(Y,p);return p},
argPackAdvance:8,readValueFromPointer:ob,J:function(n){Y(n)}})},m:function(a,b){b=K(b);Q(a,{ka:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},p:function(){z()},n:function(a,b,c){C.copyWithin(a,b,b+c)},o:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{la.grow(Math.min(2147483648,d)-ya.byteLength+65535>>>16);Ea();var e=1;break a}catch(f){}e=
void 0}if(e)return!0}return!1}};
(function(){function a(e){g.asm=e.exports;la=g.asm.q;Ea();Fa=g.asm.s;Ha.unshift(g.asm.r);G--;g.monitorRunDependencies&&g.monitorRunDependencies(G);0==G&&(null!==La&&(clearInterval(La),La=null),H&&(e=H,H=null,e()))}function b(e){a(e.instance)}function c(e){return Pa().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){A("failed to asynchronously prepare wasm: "+f);z(f)})}var d={a:Jb};G++;g.monitorRunDependencies&&g.monitorRunDependencies(G);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return A("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){return B||"function"!==typeof WebAssembly.instantiateStreaming||Ma()||I.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(I,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){A("wasm streaming compile failed: "+f);A("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ca);return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.r).apply(null,arguments)};
var yb=g.___getTypeName=function(){return(yb=g.___getTypeName=g.asm.t).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.u).apply(null,arguments)};var Ib=g._malloc=function(){return(Ib=g._malloc=g.asm.v).apply(null,arguments)},Y=g._free=function(){return(Y=g._free=g.asm.w).apply(null,arguments)},Kb;H=function Lb(){Kb||Mb();Kb||(H=Lb)};
function Mb(){function a(){if(!Kb&&(Kb=!0,g.calledRun=!0,!ma)){Qa(Ha);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Ia.unshift(b)}Qa(Ia)}}if(!(0<G)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ka();Qa(Ga);0<G||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=Mb;
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Mb();


  return Matrix.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Matrix;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Matrix; });
else if (typeof exports === 'object')
  exports["Matrix"] = Matrix;
